### ISSUE TITLE
System turning off immediately after turning on after 5.1.0 update

### ISSUE THREAD

**Issue by dizzydnallov** [jmcollin78/versatile_thermostat#299] opened 2023-12-30 01:57 UTC
Since  5.1.0 update, the AC systems that I control via five different Versatile thermostats will turn on when instructed and then immediately turn off.  I can see this when watching my unit; everything turns on, then the green light on my unit goes off, and it shuts down.  I have to cycle on/off several times for it to engage.

It was fine before the update.  Have enabled logs and attached those below

## Version of the custom_component

5.1.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, auto, cool, dry, heat, fan_only
min_temp: 16
max_temp: 32
fan_modes: auto, 1 Lowest, 2 Low, 3 High, 4 Highest
preset_modes: none
swing_modes: Up/Down Auto, Highest, Middle, Normal, Lowest, 3D Auto
current_temperature: 20.8
temperature: 21.5
fan_mode: auto
preset_mode: none
swing_mode: Up/Down Auto
is_on: false
hvac_action: null
hvac_mode: off
type: null
frost_temp: 0
eco_temp: 0
boost_temp: 0
comfort_temp: 0
frost_away_temp: 16
eco_away_temp: 16
boost_away_temp: 16
comfort_away_temp: 16
power_temp: null
target_temperature_step: null
ext_current_temperature: 4.2
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 21.5
saved_hvac_mode: null
window_state: off
motion_state: null
overpowering_state: null
presence_state: null
window_auto_state: off
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2023-12-30T01:16:22.310408+00:00
last_ext_temperature_datetime: 2023-12-30T01:03:45.104829+00:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: 2023-12-30T01:16:22.314369+00:00
timezone: Europe/London
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
temperature_unit: °C
is_device_active: false
ema_temp: 21.01
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.living_room
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
is_regulated: true
regulated_target_temperature: 23.5
auto_regulation_mode: auto_regulation_strong
regulation_accumulated_error: 24.899999999999995
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: auto
friendly_name: Versatile - Living Room AC
supported_features: 57
```

## Debug log

```
2023-12-29 08:30:00.019 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set target temp: 21.5
2023-12-29 08:30:00.021 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Kitchen AC - Set target temp: 21.5
2023-12-29 08:30:05.012 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set hvac mode: heat
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=False
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - regulation calculation will be done
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Regulated temp have changed to 23.5. Resend it to underlyings
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Versatile - Living Room AC-climate.living_room - Target temp have been updated due min, max of the underlying entity. new_value=24 value=24 min=16 max=30
2023-12-29 08:30:05.022 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2023-12-29 08:30:05.038 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Kitchen AC - Set hvac mode: heat
2023-12-29 08:30:05.049 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - Calling ThermostatClimate._send_regulated_temperature force=False
2023-12-29 08:30:05.049 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - regulation calculation will be done
2023-12-29 08:30:05.049 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - Regulated temp have changed to 24.0. Resend it to underlyings
2023-12-29 08:30:05.051 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Kitchen AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2023-12-29 08:30:06.243 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:06.243 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2023-12-29 08:30:06.285 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:06.286 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2023-12-29 08:30:08.364 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:08.364 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2023-12-29 08:30:08.452 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:08.453 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Kitchen AC - underlying event is received less than 10 sec after command. Forget it to avoid loop

```

**Comment by dizzydnallov** [comment] 2023-12-30 02:02
The attached picture of the logbook at 08:30:08 shows "turned off triggered by service Climate: Set target temperature".  If you look at the relevant time in the above logger that corresponds with

`2023-12-29 08:30:08.364 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None`

![Screenshot 2023-12-30 015820](https://github.com/jmcollin78/versatile_thermostat/assets/105526388/2772014f-7c80-489a-9b3a-210fbf8241a6)

**Comment by dizzydnallov** [comment] 2023-12-30 02:03
The biggest pain here is that I have my schedule all set up, but because of this issue, none of my systems are on in the morning when I get up!

**Comment by jmcollin78** [comment] 2023-12-30 12:12
Hello, If I look at your logs, it seems that the Living Room AC is turning off itself alone.
I think you have a internal regulation or mecanism that turns off your AC automatically. So VTherm is just following this state. The relevant log is the following:

`Living Room AC - Underlying climate changed. Event.new_hvac_mode is off`

This means that the underlying Living Room AC have shut off automatically itself.

Idem for the Kitchen as I can see.

You have to look this way.

**Comment by dizzydnallov** [comment] 2023-12-30 12:47
Thank you for your reply, but to confirm, I haven't changed anything my end at all - it worked fine before the update.  I have this morning downgraded to 5.0.0, and the issue has gone.

**Comment by jmcollin78** [comment] 2023-12-31 13:26
Hello, you should not stay in 5.0.0, there is annoying bug. You should try with the 5.0.1 at minima.

If I look at the release note in 5.1.0, I see nothing related to your issue. I think it is more a matter of coincidence.

The release note is here: https://github.com/jmcollin78/versatile_thermostat/releases

**Comment by dizzydnallov** [comment] 2023-12-31 17:27
Thank you again for your reply.  As noted, I downgraded to 5.0.0, and the issue has completely gone; if required, I will use 5.0.1 in the short term.  Everything works as expected; the AC turns on and stays on when I turn it on via HA, and the scheduling works fine, so to confirm, I don't have any issues before the 5.1.0 update.

To confirm, I have 5 AC units in 5 different rooms, and everyone encountered the same issue after updating to 5.1.0; none have worked right under 5.1.0.  They are all now fine after the downgrade to 5.0.0

It's not coincidental - the issue directly results from the 5.1.0 update; nothing else has changed between updates/ downgrades.  It does seem that the AC is replying with its own command, but I have nothing to initiate that command, and it only occurs after the update; I will look at the HACs integration I use for the AC system and report back, but very little I can change that side, and 

I will try again with 5.1.0 and update with the results.  I've already tried to remove and re-add all VersatileThermostats with no result.  Something else I could try is removing the actual AC systems on HA and then re-adding, but that's a bit of a pain, so I will hold off to see if there is any resolution here.

**Log Under 5.1.0**

```
2023-12-29 08:30:00.019 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set target temp: 21.5
2023-12-29 08:30:05.012 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set hvac mode: heat
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=False
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - regulation calculation will be done
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Regulated temp have changed to 23.5. Resend it to underlyings
2023-12-29 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Versatile - Living Room AC-climate.living_room - Target temp have been updated due min, max of the underlying entity. new_value=24 value=24 min=16 max=30
2023-12-29 08:30:05.022 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2023-12-29 08:30:06.243 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:06.243 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2023-12-29 08:30:08.364 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-29 08:30:08.364 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
```
 
**Log Under 5.0.0**

```
2023-12-31 08:30:00.017 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set target temp: 21.5
2023-12-31 08:30:00.018 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=True
2023-12-31 08:30:00.018 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - regulation calculation will be done
2023-12-31 08:30:00.018 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Regulated temp have changed to 26.5. Resend it to underlyings
2023-12-31 08:30:00.020 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=False
2023-12-31 08:30:00.020 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - period (0.0) min is < 5 min -> forget the regulation send
2023-12-31 08:30:05.013 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Set hvac mode: heat
2023-12-31 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=False
2023-12-31 08:30:05.015 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - period (0.1) min is < 5 min -> forget the regulation send
2023-12-31 08:30:05.017 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile - Living Room AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2023-12-31 08:30:06.235 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2023-12-31 08:30:06.235 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile - Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
```

**Comment by jmcollin78** [comment] 2024-01-01 16:28
Hello, I will have a look another time. Thanks for the 2 logs.

**Comment by dizzydnallov** [comment] 2024-01-01 16:37
Thanks - to confirm, I updated again to 5.1.0 yesterday and had the same issues.  I am now running on 5.0.1, and it's completely fine.  Something in that 5.1.0 doesn't like my system!

Happy to stay on 5.0.1, but hope it can be resolved :-)

**Comment by jmcollin78** [comment] 2024-01-01 17:03
I fix something on the feature which have been introduce with the 5.1.0 (check min and max value before sending the target temperature).
And I add more log for your case. Can you please give a try to the 5.1.1 just released now: https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.1.1

And let me know with the log please.
There is something weird specifically with your env. Else everybody should have the problem. What we have to do is to understand why this weird thing only happens in 5.1.0. That is why I add more logs.

**Comment by dizzydnallov** [comment] 2024-01-07 01:36
@jmcollin78 

I think I have resolved this, but I have no idea what the issue was.

I decided to go postal and removed everything relating to all AC on HA (AC Entries, Versatile & Scheduling), rebooted HA and then reinstalled everything from scratch, and it seems to be working fine now.  I still need to run through some scheduled tasks to be sure, but I'm pretty sure it's fixed.

Really strange; will confirm/ update after 24hrs

**Comment by jmcollin78** [comment] 2024-01-07 09:53
Nice to here it is working. Can you please close the issue if it is confirmed ?

**Comment by dizzydnallov** [comment] 2024-01-07 10:46
It seems I was being too optimistic; it seemed to be working fine, but randomly all my active overnight switched off, then this morning, the same issues I was having returned; all on 5.2.0

Now reverted to 5.0.1 

I tracked down the random switch-off event (which occurred in the middle of the night) in one of the bedrooms and got this in my log...

```
2024-01-07 04:46:18.130 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] Unset window auto because MAX_DURATION is exceeded
2024-01-07 04:46:18.130 WARNING (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile James Bedroom AC - End auto detection of open window slope=-3.470
2024-01-07 04:46:18.131 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile James Bedroom AC - Sending event EventType.WINDOW_AUTO_EVENT with data: {'type': 'end', 'cause': 'max duration expiration', 'curve_slope': -3.47}
2024-01-07 04:46:18.132 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile James Bedroom AC - Set hvac mode: heat
2024-01-07 04:46:18.136 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Calling ThermostatClimate._send_regulated_temperature force=False
2024-01-07 04:46:18.136 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - regulation calculation will be done
2024-01-07 04:46:18.137 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - dtemp (0.0) is < 0.5 -> forget the regulation send
2024-01-07 04:46:18.145 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile James Bedroom AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2024-01-07 04:46:18.149 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] %s - Force resent target temp cause we turn on some over climate
2024-01-07 04:46:18.149 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Calling ThermostatClimate._send_regulated_temperature force=True
2024-01-07 04:46:18.149 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - regulation calculation will be done
2024-01-07 04:46:18.149 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Regulated temp have changed to 16.5. Resend it to underlyings
2024-01-07 04:46:19.426 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2024-01-07 04:46:19.426 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2024-01-07 04:46:21.602 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2024-01-07 04:46:21.602 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2024-01-07 04:47:10.055 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - Calling ThermostatClimate._send_regulated_temperature force=False
2024-01-07 04:47:10.056 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile James Bedroom AC - period (0.9) min is < 5 min -> forget the regulation send
```

**Comment by dizzydnallov** [comment] 2024-01-07 10:54
And log for the Living room, which again failed to stay on this morning

`
2024-01-07 08:30:00.018 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Living Room AC - Set target temp: 21.5
2024-01-07 08:30:05.035 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Living Room AC - Set hvac mode: heat
2024-01-07 08:30:05.036 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - Calling ThermostatClimate._send_regulated_temperature force=False
2024-01-07 08:30:05.037 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - regulation calculation will be done
2024-01-07 08:30:05.037 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - Regulated temp have changed to 23.0. Resend it to underlyings
2024-01-07 08:30:05.038 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Living Room AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.HEAT: 'heat'>}
2024-01-07 08:30:06.228 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - Underlying climate changed. Event.new_hvac_mode is heat, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2024-01-07 08:30:06.228 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
2024-01-07 08:30:08.388 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=heat, new_hvac_action=None, old_hvac_action=None
2024-01-07 08:30:08.388 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Living Room AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
`

**Comment by jmcollin78** [comment] 2024-01-07 10:57
So this is confirmed. The underlying switch off alone:
```
Underlying climate changed. Event.new_hvac_mode is off,
```

**Comment by dizzydnallov** [comment] 2024-01-07 11:08
Okay, understand, but it worked fine before 5.1.0 update; reverting to 5.0.1 resolves all issues - I never had a random switch off at 4am, and the schedule worked perfect?  Nothing else has changed besides this component, so something must have changed to cause a conflict with my AC.

If there is nothing you can do, then I will stick with 5.0.1.  I will keep looking at my end to see what else I can garner.

**Comment by dizzydnallov** [comment] 2024-01-07 12:00
Hmmm - so, my AC Integration with HA (via HACS) seems to be outdated.  I just found this PR, which was in October; the most recent release of the Integration was in June.  I'm wondering if the issue here is timing, and the newer versatile_thermostat release has just tipped over where issues occur.   I also see that somebody has reported a bug that looks similar to mine but was resolved by implementing the PR; sound promising

I'm going to apply it and see what happens; I will report back

https://github.com/jeatheak/Mitsubishi-WF-RAC-Integration/pull/61

**Comment by dizzydnallov** [comment] 2024-01-07 15:26
I _think_ that may have solved it - not counting any chickens yet; a tad confused about the random switch-off overnight.  I will leave in 5.2.0 for a couple of days and then close if everything works as expected or resort back.

**Comment by jmcollin78** [comment] 2024-01-07 16:22
Great news. The coincidence are sometimes very confusing. Because, VTherm have now many users, if there were a regression like this, i should be drowned of bug report. That is my best argument.

**Comment by dizzydnallov** [comment] 2024-01-08 11:05
I can confirm that teh issue in my OP has been resolved, but I have this new issue where units are switching off during the night for no apparent reason.

It seems to be related to "WINDOW_AUTO_EVENT", but I have no window sensors, and it is not active on Vstat (window_state: off)

Do you want me to close this and open a new issue page?

```
2024-01-08 09:21:38.915 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Master Bedroom AC - Calling ThermostatClimate._send_regulated_temperature force=False
2024-01-08 09:21:38.916 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Master Bedroom AC - period (2.6) min is < 5 min -> forget the regulation send
2024-01-08 09:22:34.604 WARNING (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Master Bedroom AC - Start auto detection of open window slope=-3.140
2024-01-08 09:22:34.605 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Master Bedroom AC - Sending event EventType.WINDOW_AUTO_EVENT with data: {'type': 'start', 'cause': 'slope alert', 'curve_slope': -3.14}
2024-01-08 09:22:34.606 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Master Bedroom AC - Set hvac mode: off
2024-01-08 09:22:34.611 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Versatile Master Bedroom AC - Sending event EventType.HVAC_MODE_EVENT with data: {'hvac_mode': <HVACMode.OFF: 'off'>}
2024-01-08 09:22:36.461 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Master Bedroom AC - Underlying climate changed. Event.new_hvac_mode is off, current_hvac_mode=off, new_hvac_action=None, old_hvac_action=None
2024-01-08 09:22:36.461 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Versatile Master Bedroom AC - underlying event is received less than 10 sec after command. Forget it to avoid loop
```

**Closed** 2024-01-08 21:46 UTC
Labels: invalid, question
