### ISSUE TITLE
Adding min and max target temperatures attributes on the underlying entity for a vThern over climate (air conditioner)

### ISSUE THREAD

**Issue by ngthwi** [jmcollin78/versatile_thermostat#714] opened 2024-12-17 02:32 UTC
I need to lower the min and max temperature that the vTherm sets on the underlying climate.

Blowing too cold or too hot air from an air conditioner isn't really comfortable especially in a small room.
For instance in heating mode, the vTherm sets the target temperature up to 30°C but 26°C would be definitely more comfortable even though heating the room is slower...

Thanks a lot for your great project.

**Comment by jmcollin78** [comment] 2024-12-17 21:47
Hello @ngthwi ,

VTherm sets the setpoint to the value you set. How is that possible that you obtain 30° if you don't request this value ?

**Comment by ngthwi** [comment] 2024-12-20 02:39
Here's an example:
- Current temp: 16°C
- vTherm setpoint: 19°C
The underlying thermostat increases its own setpoint (19 to 30°C) until the the vTherm setpoint us reached (sorry for oversimplifying the actual process).
Isn't how is supposed to work Versatile Thermostat on an air conditioner?

**Comment by jmcollin78** [comment] 2024-12-20 07:53
Hello, ok I suppose you use self-regulation in a strong way. If you want to lower the max, then use lower level of self-regulation.

Please post me your VTherm attributes so that I can confirm you are in that case.

**Comment by ngthwi** [comment] 2024-12-22 01:57
```hvac_modes: fan_only, dry, cool, heat, heat_cool, off
min_temp: 16
max_temp: 22
target_temp_step: 0.1
fan_modes: Auto, Silence, 1, 2, 3, 4, 5
preset_modes: none, frost, eco, comfort, boost
swing_modes: Off, Vertical, Horizontal, 3D
current_temperature: 19.1
temperature: 21
fan_mode: Auto
hvac_action: heating
preset_mode: none
swing_mode: 3D
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 7
eco_temp: 19
boost_temp: 20
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 10
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 20
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-22T02:41:56.234417+01:00
last_ext_temperature_datetime: 2024-12-22T02:41:56.234417+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 3.5
mean_cycle_power: null
total_energy: 0.18
last_update_datetime: 2024-12-22T02:42:57.252460+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
device_actives: climate.salon
nb_device_actives: 1
ema_temp: 19.1
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
is_over_climate: true
start_hvac_action_date: 2024-12-22T02:42:57.248178+01:00
underlying_entities: climate.salon
is_regulated: true
regulated_target_temperature: 20
auto_regulation_mode: auto_regulation_expert
regulation_accumulated_error: 0
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: true
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
auto_start_stop_last_switch_date: null
follow_underlying_temp_change: false
friendly_name: vTherm Salon
supported_features: 441 ```

**Comment by ngthwi** [comment] 2024-12-22 02:04
https://github.com/user-attachments/assets/d7e7c90a-9f47-4a40-bb82-a81af43aa243

**Comment by ngthwi** [comment] 2024-12-22 02:10
In this example, I'd like the underlying temperature (on the left) not to go over 26°C.

https://github.com/user-attachments/assets/bac7aa82-d59b-4d17-bd73-a1fbd458f094

**Comment by jmcollin78** [comment] 2024-12-22 08:25
Hello, you use the expert regulation mode `auto_regulation_mode: auto_regulation_expert` with certainly some very strong regulation values. You can adjust the `offset_max` so that the maximum value will be contained.
But the objective of the expert regulation mode is to have a large `offset_max` so you have some contradictory injunctions in your case.

**Comment by ngthwi** [comment] 2024-12-22 11:48
Thanks for your quick answer.
Where can I set `offser_max`? 
I don't see it among the attributes...

About `auto_regulation_expert`, isn't that the correct setting when there a" > 5°C" gap between the temperature sensors of the underlying climate (air con) and the "good" (external) sensors?

**Comment by ngthwi** [comment] 2024-12-22 13:00
Despite having set `offset_max:  6`
I have the underlying target temperature more than 6°C over the vTherm setpoint... 

![IMG_1795](https://github.com/user-attachments/assets/e2b160b5-975d-4d3e-a80f-93194faf4955)

Here's my `auto_regulation_expert` setting:

```versatile_thermostat:
  auto_regulation_expert:
    kp: 0.6
    ki: 0.1
    k_ext: 0.0
    offset_max: 6
    stabilization_threshold: 0.1
    accumulated_error_threshold: 80

**Comment by jmcollin78** [comment] 2024-12-22 15:18
Yes, you have to uncheck this: `auto_regulation_use_device_temp: true`
Else VTherm will add the compensation offset.

**Comment by jmcollin78** [comment] 2024-12-22 15:19
I will close the issue because it is not an issue but wa can continue the discussion if you need it.

**Closed by jmcollin78** 2024-12-22 15:19 UTC
Labels: invalid, question

**Comment by ngthwi** [comment] 2024-12-22 15:52
> Yes, you have to uncheck this: `auto_regulation_use_device_temp: true` Else VTherm will add the compensation offset.
> 
> It is rarely a good idea to cumulate the both.

That would defeat the purpose of using your excellent Versatile Thermostat, wouldn’t it? ;)

Here’s my situation: I need a thermostat that displays accurate temperature setpoints and values because the ones on my air conditioner (Daikin) are completely off and unreliable.

The only issue I’m facing is that the maximum temperature setpoint on the underlying thermostat is too high to be comfortable. If I’m under the air stream, 30°C feels too hot, while 26°C is fine.

If `offset_max` is the correct setting to cap the maximum setpoint on the underlying thermostat, why does it show 27°C when `offset_max: 6`, while the vTherm setpoint is set to 19°C?

----

Ce serait contre-productif d’utiliser ton excellent Versatile Thermostat, non ? ;)

Mon utilisation est d'avoir d’un thermostat qui affiche des consignes et des valeurs de température précises, car celles de mon climatiseur (Daikin) sont totalement incorrectes et peu fiables.

mon souci est que la consigne maximale de température sur le thermostat sous-jacent est trop élevée pour être confortable. Si je suis sous le flux d’air, 30 °C est trop chaud, tandis que 26 °C est acceptable.

Si `offset_max` est le bon paramètre pour limiter la consigne maximale, pourquoi le thermostat sous-jacent affiche-t-il 27 °C avec `offset_max: 6`, alors que la consigne du vTherm est réglée à 19 °C ?

**Comment by jmcollin78** [comment] 2024-12-22 16:29
Parce-que tu as sélectionné :
![Uploading Capture d’écran 2024-12-22 à 17.26.53.png…]()

Donc tu ajoutes à la régulation la compensation de la température interne de ton device qui comme tu le dis toi même est fausse. Décoches cette option et laisse l'auto-régulation sur expert et ça devrait être bon.

Comme dit dans la doc: https://github.com/jmcollin78/versatile_thermostat/blob/main/documentation/fr/over-climate.md#compenser-la-temp%C3%A9rature-interne-du-sous-jacent

```
Attention toutefois, certaines températures internes varient tellement vite et sont tellement fausses qu'elles faussent totalement le calcul. Dans ce cas, là, il vaut mieux désactiver cette option.

```
