### ISSUE TITLE
vtherm over dummy/template switch not working. 

### ISSUE THREAD

**Issue by tbrasser** [jmcollin78/versatile_thermostat#414] opened 2024-03-19 10:07 UTC
## Version of the custom_component
latest

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 15
max_temp: 25
target_temp_step: 0.1
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
  - activity
current_temperature: 21.1
temperature: 15
hvac_action: idle
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: Auto
frost_temp: 7
eco_temp: 18
boost_temp: 22
comfort_temp: 20
frost_away_temp: 7
eco_away_temp: 7
boost_away_temp: 7
comfort_away_temp: 7
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 11.07
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 15
saved_hvac_mode: null
motion_sensor_entity_id: binary_sensor.area_eetkamer
motion_state: "on"
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: binary_sensor.area_interior
presence_state: "on"
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-03-19T10:40:46.745511+01:00"
last_ext_temperature_datetime: "2024-03-19T10:56:10.304835+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: 0
last_update_datetime: "2024-03-19T10:59:49.124897+01:00"
timezone: Europe/Amsterdam
temperature_unit: °C
is_device_active: false
ema_temp: 21.05
is_used_by_central_boiler: true
is_over_switch: true
is_inversed: false
underlying_switch_0: input_boolean.dummy_eetkamer_trv
underlying_switch_1: null
underlying_switch_2: null
underlying_switch_3: null
on_percent: 0
power_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: null
tpi_coef_ext: null
friendly_name: Eetkamer
supported_features: 401

```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug

I'm trying to:

Use vtherm over switch on input boolean to spoof smart TRVs on radiators/areas where I have none yet. 

And I expect:

It to toggle the template switch 

But I observe this ....

![Screenshot_2024-03-19-10-26-35-618_io.homeassistant.companion.android.jpg](https://github.com/jmcollin78/versatile_thermostat/assets/2816560/7b1bd9b8-a07b-4a6d-9e70-d2df2d6919d5)

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/versatile_thermostat/prop_algorithm.py:81
integratie: Versatile Thermostat (documentation, issues)
First occurred: 10:40:46 (8 gebeurtenissen)
Laatst gelogd: 11:06:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1436, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_switch.py", line 182, in recalculate
    self._prop_algorithm.calculate(
  File "/config/custom_components/versatile_thermostat/prop_algorithm.py", line 81, in calculate
    self._tpi_coef_int * delta_temp
    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
 

```

**Comment by jmcollin78** [comment] 2024-03-19 18:36
You have not configured TPI:
```
tpi_coef_int: null
tpi_coef_ext: null
```

That is the root cause of the error. But it should not be possible. Are you in V6.0 ?

**Comment by jmcollin78** [comment] 2024-03-23 08:15
I cannot reproduce this case.

**Comment by tbrasser** [comment] 2024-03-23 09:27
Seems some settings don't persist. I loose presence feature every time I re configure a vtherm. I solved it by going top to bottom through all the settings without skipping any page.

**Comment by jmcollin78** [comment] 2024-03-23 10:51
Do you have a Central configuration ?

**Comment by tbrasser** [comment] 2024-03-27 21:05
> Do you have a Central configuration ?

Yes. Every time I restart home assistant I have to re enable presence in the features of every vtherm.

**Comment by jmcollin78** [comment] 2024-04-01 10:47
Hello, I cannot reproduce your case but I suspect a misconfiguration in the central configuration presence feature.
Can you please show me a screen copy of the central configuration presence feature
AND the same for a normal VTherm ?

You should have something like that:
For central configuration:
![Capture d’écran 2024-04-01 à 12 45 44](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/c37aac31-d085-4cb7-b3cd-8a99673898d1)

For normal VTherm configuration:
![Capture d’écran 2024-04-01 à 12 46 35](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/5a78dc12-0188-415f-961f-109c074a2e9a)
Then click on presence feature:

![Capture d’écran 2024-04-01 à 12 47 24](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/f98360ce-19b5-4aa6-a826-8d835f39a443)

**Comment by jmcollin78** [comment] 2024-04-02 18:52
VTherm have all features from Better Thermostat since 5.4 release. 
Pure switch device (like yours), BT doesn't do more than VTherm. I don't known why you think it is a good idea to have a BT.
Tries without and everything should be fine.

**Comment by tbrasser** [comment] 2024-04-03 20:11
I have 3 vtherm over climate for TRVs. And 3 'dummy' vtherm over switch. Then I have 1 non vtherm central boiler climate device (not on-off) on which I set both the target and current temperature with those from the 6 with the highest heating demand. Good to know vtherm fully supercedes bt. Will remove it.

**Comment by tbrasser** [comment] 2024-04-04 06:51
Without bt in between my smart TRVs and vtherm over climate I don't get to see the current action of 2 out of 3 of my TRVs (the middle 2 'kantoor' and 'keuken':

![Screenshot_2024-04-04-08-50-29-987_io.homeassistant.companion.android.jpg](https://github.com/jmcollin78/versatile_thermostat/assets/2816560/8b50e3a8-ea4b-460f-802f-aac75e1959b4)

**Comment by jmcollin78** [comment] 2024-04-06 07:19
> I don't get to see the current action of 2 out of 3 of my

To be sure when you said the "current action" you mean the attribute havc_action isn't set ? May I have the attributes of one of this VTherm ? Is the attribute hvac_action set ?

**Comment by tbrasser** [comment] 2024-04-06 08:11
That is indeed what I think is happening (and why I put better-thermostat in between for those two smart TRVs.

So I own 4 different brands now and not a single one of them is 'perfect'.

Either current hvac action is missing, and none of them allow control of the valve directly.

Aqara E1 (allows using external sensor as current_temperature, no valve control, no hvac_action) 

Bosch trv 2 (allows using external sensor as current_temperature, no valve control, do get valve status, do get hvac_action) 

Sonof trvzb (no external sensor support, no valve control, no valve status, do get hvac_action) 

Moes/tuya/something (no external sensor support, no valve control, no valve status, no hvac_action).

What setup would you recommend?

**Comment by jmcollin78** [comment] 2024-04-07 06:52
Yes I have users that uses the Shelly TRV with success. The valve is directly controlableand all features are available.

**Comment by jmcollin78** [comment] 2024-04-16 04:49
I will close this issue which not related to VTherm. Reopen if you think I'm wrong.

**Closed by jmcollin78** 2024-04-16 04:49 UTC
Labels: bug, question, P1, not reproduced
