### ISSUE TITLE
Warning messages after upgrade to version 6.0

### ISSUE THREAD

**Issue by mleiber** [jmcollin78/versatile_thermostat#411] opened 2024-03-17 07:48 UTC
Just updated to version 6.0, here's what's now seen in the logs. I wonder if there is any manual intervention needed to adapt the new handling of the presets? I have checked the new entities eg. `number.heating_wohnhalle_preset_boost`, they all seem to be properly migrated. I also went through the new configuration process for all of the VTherms and confirmed they are complete.

I noticed though that in the configuration dialog in the `Presets` section does not show a panel to enter the presets - on the top level the menu entry exists, then leads to the question if I use a central configuration - which I don´t - then jumps back to the main menu. I would expect to be able to set the presets here, not just via the `number` entities.

A further note on the `WARNING` messages itself, you may want to consider to add the affected `entity_id` in the text, hard to tell otherwise which of the VTherms is in 'trouble'. In this case it's easy as they are all flagged. For the first 4 warnings there's actually an `Entity None` in the text, maybe that one is supposed to be the reference to the VTherm. 

```
2024-03-17 08:09:26.832 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.versatile_thermostat.thermostat_switch.ThermostatOverSwitch'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues
2024-03-17 08:09:26.857 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.versatile_thermostat.thermostat_switch.ThermostatOverSwitch'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues
2024-03-17 08:09:26.871 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.versatile_thermostat.thermostat_switch.ThermostatOverSwitch'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues
2024-03-17 08:09:26.897 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.versatile_thermostat.thermostat_switch.ThermostatOverSwitch'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jmcollin78/versatile_thermostat/issues

2024-03-17 08:09:31.043 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
2024-03-17 08:09:32.040 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
2024-03-17 08:09:32.056 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
2024-03-17 08:09:32.074 WARNING (MainThread) [custom_components.versatile_thermostat.prop_algorithm] Proportional algorithm: calculation is not possible cause target_temp or current_temp is null. Heating/cooling will be disabled
```

**Comment by jmcollin78** [comment] 2024-03-17 08:56
Duplicate of #338.

**Closed by jmcollin78** 2024-03-17 08:56 UTC
Labels: duplicate

**Comment by mleiber** [comment] 2024-03-17 09:04
are you sure that this is a duplicate of #338 - that one looks very different - as far as my spotty French knowledge allows me to judge.

**Comment by mleiber** [comment] 2024-03-17 09:10
oh, looks like you meant #388 !

**Comment by jmcollin78** [comment] 2024-03-17 23:26
Yes your right. It was #388
