### ISSUE TITLE
Early turning on of the heater

### ISSUE THREAD

**Issue by mmazzuro** [jmcollin78/versatile_thermostat#165] opened 2023-11-05 23:41 UTC
jmcollin78, I would like to propose adding the following features to the versatile_thermostat if you find them interesting.
1) Setting for the holiday with automatic insertion by querying the Holiday integration of the country of residence, makes versatile_thermostat smart when the holiday falls on a weekday.
2) Allow the thermostat to reach the setting temperature at the scheduler time, for example if the comfort temperature is set at 08:00 the thermostat should activate the heater in advance to reach the setting at the desired time knowing the performance of the heat generator warmth after a few days of learning.

**Additional context**

**Comment by jmcollin78** [comment] 2023-11-06 00:15
Hello,

Oooh, that is a great news !

1. I don't know the Holiday integration but it sounds great.
2. before I can answer, how do you intend to do the heating in advance feature ? I wish to avoid something too much complex before configuration is already complex. If you have a simple idea on how to do that why not. But personaly I've got no idea, on how to do that (you must have the heating time I guess somewhere).

**Comment by adi90x** [comment] 2023-11-06 09:10
Hello,

On 2nd point, can't we store in vtherm how long it takes to increase by one degree ( same kind of slope computation than used for windows open) and then applied that maybe thanks to scheduler component ( to avoid reimplementation of scheduling) ?

**Comment by maia** [comment] 2023-11-06 10:15
@adi90x Instead of having a couple of float/integer variables that users need to define, I suggest 3-5 options for the latency of the building construction and heating system, from "heats slowly, but keeps temperature well" to "heats very quickly, but without heater it gets cold very quickly". The internally used variables for pre-heating, regulated heating, windows,… would be deducted from this single option. This way a) future builds of VTherm can optimise without the users needing to change anything and b) users aren't overwhelmed by things they can't quickly answer and don't understand in detail.

**Comment by adi90x** [comment] 2023-11-06 10:25
@maia : In my idea, user don't select any parameters, heating time is computed by the vtherm itself, then we just need to think about the calling logic but something could be a new service with : on/off, date/time, preset as parameters, whenever receive the vtherm compute when it need to switch to preset temp by just multiplying : targeted temp* computed heating slope ( I. E time to get 1°). At each cycle, this can be recomputed to take into account natural cooling/heating of the room.
In this anticipation mode, we will need also a new attribute to make it clear to user that pre heating is on.

**Comment by maia** [comment] 2023-11-06 10:31
Calculating the latency would be great for many aspects, but it's pretty hard to come up with an algorithm as you'd need many cases to analyse (at least a dozen?) and would need to calculate a regression based on outdoor temp, target temp, room temp, temp measured at the valve, valve opening percentage, sunshine, presence of people, showering/taking a bath, cooking,…

But by the way, isn't the entire scheduling part something outside of VTherm, e.g. with scheduler-card? In that case the pre-heating is something that would need to be added to scheduler-card, as it knows when to use which preset.

**Comment by jmcollin78** [comment] 2023-11-06 15:15
Hello @adi90x ,

Here an example curve of heating:
![Capture d’écran 2023-11-06 à 16 10 55](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/1ccc90f7-b887-482b-992d-ba4555d48c44)

Can you tell me, the time needed to increase 1° ?
I guess not, this is very complex and depending of many conditions that will make this feature not accurate.

More-over having a kind of internal planner in VTherm which could be in contradiction with the Scheduler orders is tricky.
So, I'm not going to do this unless we come up with a simple and brilliant idea. The risk for me is to spend hours in support because this don't works in so many cases. I don't have time to do that (the support takes me already many times).

**Comment by adi90x** [comment] 2023-11-06 16:50
Hello @jmcollin78,

I agree it won't be perfectly accurate but I would have computed it at each
cycle :
 ``` (Temp end of cycle-Temp beginning cycle) * 60 / (
on_percent*cycle_time) ```
Given this you have an estimate of how efficient your heater is ( probably
need to avoid computation if on_percent = 0, to always keep last heating
efficiency estimation.
Given this parameters, we can either start/stop heating earlier with the
logic I shared before, or we can stop at this step and then user can setup
automation/scheduler based on how efficient is there heater ?
Even for statistic, this information could be interesting and at some point
in the future it could even be integrated into heating algo.

Regards,

**Comment by maia** [comment] 2023-11-06 16:55
@adi90x How would you deal with TRVs? They don't have a binary on/off but a constantly adapting valve position. And is the "cycle" you're referring to the time of a preset, which can be many hours?

**Comment by adi90x** [comment] 2023-11-06 17:04
@maia : we could do the computation using valve position instead of on_percent.
Should give us an idea of how long it take at 100% valve to gain 1degree, with that info you should be able to adjust valve percent and or start time to reach expected temp at expected time.

**Comment by mmazzuro** [comment] 2023-11-06 22:50
Good evening,
I'm glad I gave such an interesting and full of interest idea.
So for point 1 in my installation I developed it by creating a binary sensor that is activated via the Holiday integration taken from HACS here https://github.com/bruxy70/Holidays, I set Italy in the calendar and the holidays automatically come out . Already tested with 01/11 a national holiday for us.
I saw that Homeassistant has its own integration called Workday https://www.home-assistant.io/integrations/workday/ which is ultimately the same thing, but I discovered it late.
In the scheduler proposed in the versatile_thermostat documentation I created 3 schedules, weekdays, weekends, holidays.
In the programming it allows you to insert a condition, so I inserted the test to the binary sensor created above for the selection of the setting.

For point 2 I will explain how it works on my 2004 Honeywell CM907 programmable thermostat.
The chronothermostat has a very efficient PID type regulation algorithm.
During the first commissioning for a week in reaching the set temperature I think it memorizes the time for the temperature to rise and therefore creates its own response curve between the rise and fall time for the dispersions of the casing.
The behavior is always very punctual, and on the coldest mornings jumping out of bed to go to work with the right heat at the desired time is priceless. The algorithm certainly adjusts itself with the variables mentioned above by the participants for any heat inputs that cannot be predicted a priori, but I must admit that even without the external sensor it always manages to hit my request in the right time.
The regulation occurs according to the number of cycles per hour, minimum operating time, proportional band (a sort of error/hysteresis around the desired setting) type of heating, electric or methane. Mine is set to 6 cycles per hour, therefore every 15 minutes and with a proportional band of 1.25 °C, methane system and minimum time of 5 minutes.
Of course, the non-presence of Chrono in the versatile_thermostat code
makes implementation difficult, but not impossible. Unfortunately I don't know how to write in Python otherwise I could have contributed.
Now I'm testing versatile_thermostat which I really like to make my system smart. It's still very hot here and I can't see the results by connecting versatile_thermostat to the clean contact of the boiler.
Now I'm going to see the 4.0 I'm curious!!!!

**Comment by maia** [comment] 2023-11-07 05:24
@adi90x I'm not against the idea. I just think it's quite challenging. E.g. my boiler only turns on when heat is needed in the living room, as that's where it has its room sensor controlling the boiler. Currently it turns on 1-6 times per hour to heat for a minute. So when another room needs a temperature increase, it'll have to wait until the next gas burning cycle. That can be in a minute, it can be in 45 minutes. And frequently (if it's not too cold outdoor) the boiler is on for such a short time that many radiators don't really get warm. It's a poorly planned system with a boiler 3x (!) as large as necessary, making its control terribly hard. That's an extreme situation, but it's an example for the challenge of calculating the time it needs to heat a room by a degree.

**Comment by adi90x** [comment] 2023-11-07 11:14
Hello,

Fully agree, pre-heating will be a nightmare for long cycle / long
responsive heater.
I have try to put something up yesterday evening ( using a gaz boiler
heater, so also pretty long to response), will test/tune it for 2/3 days to
see if it works ( and will also test it against quick electric heater this
week-end )
If it is conclusive, will see how to share it either inside vtherm or as a
standalone component.

Regards,
Adrien

**Comment by jmcollin78** [comment] 2023-11-07 22:01
There is two points in one discusion and it is so difficult to follow. @mmazzuro can you please rename this discussion for the point 2 only and create a new one with only the point 1 ?

Thank you in advance,

**Comment by ghostsam45** [comment] 2023-11-09 19:09
Hello,

Je partage l'avis de @mmazzuro
Je dispose au RDC d'un poêle à granule contrôlé par Netatmo thermostat qui gère très bien automatiquement l'heure de début de chauffe pour atteindre la température à l'heure demandée suivant je l'imagine un algorithme qui prends en compte le temps de chauffe, la température extérieur et intérieur actuelle.

exemple: planification à 7h pour 19°, allumage à 6h27 pour l'atteindre
<img width="383" alt="netatmo" src="https://github.com/jmcollin78/versatile_thermostat/assets/64093962/852a213a-b7fe-492d-8a6f-2008efbe5c70">

à l'étage, je dispose de radiateur électrique connecté que je gère avec Home Assistant avec une heure approximative que j’estime pour atteindre la température cible au moment voulu (ce qui est très aléatoire suivant la température extérieure)

exemple: planification et allumage à 6H pour espérer atteindre la température cible à 7H
<img width="405" alt="radiateur" src="https://github.com/jmcollin78/versatile_thermostat/assets/64093962/c3136482-aa4a-412f-a989-f93cfd65db86">

Une telle option serait un grand plus pour cette intégration mais pas évident sachant que la planification est externe.

**Comment by jmcollin78** [comment] 2023-11-10 23:07
I understand the need but I still have no idea on how to implement this simply for all kinds of VTherm without to have to implement an internal scheduler and adding some more parameters than the 60 already existing.

I will keep this issue open for a while waiting for a brillant idea.

Waiting for the idea, you "just" have to anticipate the starting time in your scheduler to anticipate the duration of heating. I think all people like me does that naturally without even thinking about that.

**Comment by jmcollin78** [comment] 2023-11-16 23:28
I close the issue. Please continue into the discussion section if needed

**Closed by jmcollin78** 2023-11-16 23:28 UTC
Labels: wontfix, Waiting response
