### ISSUE TITLE
`thermostat_over_valve` the target temperature is already reached by a few degrees, but VT keeps the valve opening at 100% and heats way too much.

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#654] opened 2024-11-21 06:13 UTC
I have a similar problem, but I'm using the `thermostat_over_valve` type. The target temperature is already reached by a few degrees, but VT keeps the valve opening at 100% and heats way too much.

For that thermostat type, there is no `Follow the under...`, right?

I also can't change the preset anymore. The preset icons in the UI remain greyed out. 

The logs don't show any errors or warnings.

At some point I installed the latest Home Assistant (Core?) Update and restarted the instance. Afterwards, VT stopped heating and I could select a preset again. Anyway, I've "played around a little with different temperature and preset settings" and I'm back to the original problem: VT keeps on heating at 100% even though the target temperature has already been reached.

A while after, I noticed the opposite effect: I increased the target temperature above the current one, but VT does not start to heat.

I I wait long enough, nothing changes automatically. Anyway, if I increase the temperature even further, it suddenly updates the heating status. If I decrease the target temperature again below the current temperature, it again keeps on heating instead of stopping.

Is there maybe some internal minimum time span that needs to pass between two consecutive temperature configuration changes?

Not sure whether the additional symptoms mean that I have a different problem and shouldn't bother you in this issue.

_Originally posted by @Johnson145 in https://github.com/jmcollin78/versatile_thermostat/issues/649#issuecomment-2489705941_

**Comment by jmcollin78** [comment] 2024-11-21 06:16
Hello @johnson145,

Here we are with the issue. You seems to have a blocking HA or VTherm which is not commons.
I will absolutly need some log even if you seen nothing. See here on how to activate VTherm logs: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#enable-versatile-thermostat-logs

Put this logs on and reproduce your issue. It seems reproductible.

Thank you

**Comment by jmcollin78** [comment] 2024-11-21 06:20
> Is there maybe some internal minimum time span that needs to pass between two consecutive temperature configuration changes?

Yes there is. This is those parameters:
```
auto_regulation_dpercent: 0.1
auto_regulation_period_min: 1
```

I will see the values in your attributes. Those parameters avoid to send too much command in your TRV and then empty your battery to quickly.

**Comment by Johnson145** [comment] 2024-11-21 21:52
Thanks again for the quick response!

I didn't explicitly enable logs for VT before, sorry. Did that by now. The only interesting entries I found so far are:
```
2024-11-21 22:40:16.883 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_valve] VersatileThermostat-Heizung Küche VT - do not calculate TPI because regulation_period (0) is not exceeded
...
2024-11-21 22:43:03.823 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_valve] VersatileThermostat-Heizung Küche VT - do not calculate TPI because regulation_period (2) is not exceeded
```

I guess that also points to the previously-mentioned delays?

Of course, I currently can't reproduce the actual problem anymore... I guess it shouldn't take too long until it reoccurs though. I'll send an update if I actually recognized the same problem again.

Anyway, here are my current attributes:
```
hvac_modes:
  - heat
  - "off"
min_temp: 12
max_temp: 25
target_temp_step: 0.5
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
current_temperature: 19.6
temperature: 14.5
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat
type: null
is_controlled_by_central_mode: true
last_central_mode: null
frost_temp: 15
eco_temp: 17
boost_temp: 20.5
comfort_temp: 19
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.5
ext_current_temperature: 2
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 21
saved_hvac_mode: heat
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 180
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-11-21T22:43:03.822974+01:00"
last_ext_temperature_datetime: "2024-11-21T22:36:00.009870+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 1
total_energy: 0
last_update_datetime: "2024-11-21T22:43:03.824780+01:00"
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: true
ema_temp: 18.6
is_used_by_central_boiler: false
temperature_slope: 8.84
hvac_off_reason: null
valve_open_percent: 100
is_over_valve: true
underlying_entities:
  - number.heizung_kuche_valve_opening_degree
on_percent: 1
on_time_sec: 300
off_time_sec: 0
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
auto_regulation_dpercent: 10
auto_regulation_period_min: 5
last_calculation_timestamp: "2024-11-21T22:40:16.790067+01:00"
friendly_name: Heizung Küche VT
supported_features: 401
```

**Comment by jmcollin78** [comment] 2024-11-21 22:07
> I guess that also points to the previously-mentioned delays?

exactly !

Your values are high:
```
auto_regulation_dpercent: 10
auto_regulation_period_min: 5
```

You will have at most one change every 5 min sent to the valve and only if the open percent have change at least of 10%. So it will not change so often.

To be sure, you can activate the logs (in debug level) and search for this line: 
`do not calculate TPI because regulation_dpercent (%.1f) is not exceeded`

You will then see why the new values are not sent.

To change log you have this: https://github.com/jmcollin78/versatile_thermostat/blob/main/README.md#enable-versatile-thermostat-logs

**Comment by Johnson145** [comment] 2024-12-05 10:16
I can't reproduce this issue anymore. I don't really understand why, because it occured that often before. Anyway, I'll close this issue for now and re-open it in case it occurs again.

PS: Changing the configuration you've mentioned enhanced the overall experience for sure. It makes sense to me that you need something like that to save battery consumption caused by the algorithm. However, I didn't expect it to affect temperature changes that are directly triggered by the user. Wouldn't it make sense to distinguish between those two types of changes? Maybe not postponing user actions at all or at least using a configuration which may have less strict values?

**Closed** 2024-12-05 19:29 UTC
Labels: question
