### ISSUE TITLE
In VTherm over climate, changing target temp on underlying should update the target temp in the VTherm

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#110] opened 2023-10-01 06:56 UTC
The case is the following:
1. VTherm in over climate,
2. VTherm have a preset activated, let say Comfort,
3. Someone change the underlying cilmate target temperature,
4. EXPECTED: the VTherm goes into manual preset and the target temperature is the target temp of the underlying
5. CONSTATED: no change on VTherm

More info here: https://community.home-assistant.io/t/versatile-thermostat-a-full-feature-thermostat-energy-door-window-presence-motion-preset-management/546761/31?u=jmcollin

Thanks to @aleco !

**Comment by maia** [comment] 2023-10-01 19:26
This might be a duplicate of #101.

**Closed** 2023-10-03 05:56 UTC
Labels: duplicate
