### ISSUE TITLE
Fahrenheit conversion is not correct, seems to make the conversion twice. 

### ISSUE THREAD

**Issue by darkwolfgar** [jmcollin78/versatile_thermostat#240] opened 2023-11-30 23:42 UTC
When converting Fahrenheit temperatures to Celsius and putting the Celsius temperature in the configuration settings, this seems to be correct, See below. 
![image](https://github.com/jmcollin78/versatile_thermostat/assets/88863932/d842defb-386b-46e3-975e-a0ffe4ad0abf)
However, as shown in the picture below, the current temperature is taking the Fahrenheit temperature of my sensor and using the Fahrenheit to Celsius conversion on it again.
![image](https://github.com/jmcollin78/versatile_thermostat/assets/88863932/bb6bab7f-516f-4605-b53c-d99461ec4925)

**Comment by darkwolfgar** [comment] 2023-11-30 23:45
Also it appears that even though its showing Fahrenheit, when I set the temperature to 75, on my thermostat its setting it to 45 degrees Fahrenheit instead of 75.

**Comment by jmcollin78** [comment] 2023-12-01 06:06
It seems you are in `over_climate`. It that mode it should use the temperature unit of the underlying climate. Is the underlying climate correctly displayed ?

**Comment by jmcollin78** [comment] 2023-12-03 18:32
I never do any translation of °C to °F or reverse. I let the system do like it always does.

The unit of all VTherm is the unit configured in the HA configuration.
`self._unit = self._hass.config.units.temperature_unit` 

Is your global HA configuration set the Kelvin ?
Is your underlying climate also configured in °K ? You should be able to see that in the attributes of the climate (Dev Tools / States).

**Comment by jmcollin78** [comment] 2023-12-03 18:38
When I switch my test env with the checkox checked, I have this :

![Capture d’écran 2023-12-03 à 19 37 41](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/e43e9261-bdae-41c7-8e4b-ff326e6b5987)


This seems coherent. I guess the problem is not related to VTHerm itself.

**Comment by jmcollin78** [comment] 2023-12-03 22:36
How to you set the temperature for preset in the VTherm configuration ? Do you set the temperature in °C or °K ?

**Comment by jmcollin78** [comment] 2023-12-05 05:46
I can't understand why this behavior. Even if I configure my HA into °F I don't have this but my sensor are all in °C.
Can you please post me the attributes of the VTherm (in Development  Tools / State, find your VTherm and post the attributes in yaml formatted with the <> button).
I want to check if the unit is correctly set.

**Comment by jmcollin78** [comment] 2023-12-22 09:42
Hello @benjinne ,

I think, and maybe @darkwolfgar can confirm, that the workaround is to configure VTherm with °C temperature in all fields that need a temperature.
For an unknown reason, if temperature are typed in the local system, HA don't take it into account.

If someone is familiar with HA and metrics system, may be he could have a look of is wrong.

**Comment by jmcollin78** [comment] 2024-01-01 17:39
There have been no news from this issue. I will close it, don't hesitate to reopen if you think I'm missing something.

**Comment by MattDahEpic** [comment] 2024-03-26 01:21
I am also encountering this issue. I am not sure how to "configure VTherm with °C temperature in all fields that need a temperature" as detailed in the workaround.
![image](https://github.com/jmcollin78/versatile_thermostat/assets/7366951/84ab3c3c-565c-4acf-82ce-44668fff9370)

**Comment by bdonohoe** [comment] 2024-04-13 21:52
Same. I just tried to set up VTherm and gave up after encountering this issue.

**Comment by mbbush** [comment] 2024-05-12 01:49
I'm experiencing a variant of this same issue. I'll try to describe it in a reproducible way:

Running Versatile Thermostat v6.2.3, on home assistant container 2024.5.1

Given:
* A climate entity configured in Fahrenheit
* A room temperature sensor configured in Fahrenheit
* An outdoor temperature sensor configured in Fahrenheit
* Home assistant units set to US Customary

When:
* I create a new instance of Versatile Thermostat in "over climate" mode
* Using the default min/max temperatures of 7 and 35 (the UI gives no indication as to units)
* Without a central configuration
* Specifying a single climate entity
* With "use internal temperature of the underlying" set to true
* With AC mode enabled

Then:
* All presets are created with a default value of 95 degrees F, which is equal to 35 C

When:
* I click "configure" a second time, make no changes, and save the results

Then:
* All presets are now set to 203 degrees F (which is equal to 95 degrees C)

So it seems to me that the problem is somewhere in the configuration flow, perhaps with converting between the objects used for the config flow, and those used to persist the configuration in the database? 

Thanks for the clarification that there's no explicit unit conversion in your codebase. That means I can stop hunting for it! The remaining explanation I can think of is that it's probably some sort of implicit behavior of home assistant. If I had to guess I'd say it's most likely happening during serialization or deserialization, and might be fixable if you specified the expected unit. I haven't found a specific place in the code where this may be happening, but I'll keep looking.

Given that there are multiple people experiencing this (judging by the comments since it was closed), and (I hope) I've now given clear steps to reproduce, @jmcollin78 could you please reopen the issue?

**Comment by jmcollin78** [comment] 2024-05-13 05:39
Thank you @mbbush ,

I already spend many time trying the reproduce the problem. I will try the repro case you gave me but all my temperature sensor are in °C, so it is difficult to be in your strict repro case.

What is sure is that I never convert any temperature and I never suppose that the input is in °C. So, logically, if all your input are in °K this should work.

I set the temperature metric as the metric of the HA settings. So the temperature should be stored with °K.

> Using the default min/max temperatures of 7 and 35 (the UI gives no indication as to units)

That seems wrong. I would expect, you set it in °K.

> That means I can stop hunting for it! The remaining explanation I can think of is that it's probably some sort of implicit behavior of home assistant

That is also my guess. 

I'm looking for someone, you will be able to debug and to figure out what is missing. Have you a dev environment and all conditions to test in °K ? If yes, I was waiting for this. The best way to find what goes wrong, is to install a development environment (VScode + DevContainer make it easy), and creates some VTherm and temperature sensor with °K, and breakpoint (I can help to find the good breakpoint). 

> could you please reopen the issue?

Done

**Comment by jmcollin78** [comment] 2024-05-13 05:50
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.2.4.beta1

Please install it and give me some feedback. I only put this fix in the beta release to avoid conflict.

**Comment by mag2352** [comment] 2024-05-13 18:59
I would like to add some clarification here as well. Firstly, Home Assistant is largely responsible for these problems. As for the fix, I'm trying to figure out why certain things are happening. The above fix, and beta version made no change to my problems. In my case, I have:

- A climate entity that has an underlying unit of Celcius. (an ESPHome Midea AC)
- A temperature sensor that has a raw unit of Celcius, but HA converts it automatically to Fahrenheit.
- Outside temperature sensor that has a raw unit of Celcius, but HA converts it automatically to Fahrenheit.

Now, I'll try and explain what I've noticed. My HA is set to Fahrenheit by default. This does one main thing. The underlying climate entity (which is in Celcius) is converted to Fahrenheit (and the user has no way to change the way its represented except for changing their preferred unit in HA). 

VTherm is declaring itself as a climate entity with a unit of Celcius (assuming because the underlying entity is in Celcius). This means that the temperature sensors that have been converted to Fahrenheit by HA already (input into the VTherm) are converted to Fahrenheit again. Then, VTherm places the Fahrenheit value as the current temperature value of the climate entity. The climate entity, however, is Celsius, so this results in just the current temperature value being converted twice. I will note that this can be worked around by making a template sensor, but that is tedious. The configuration should have a setting that allows for the proper conversion (not important for usability).

Secondly, VTherm saves the values that the user sets as Celcius (it's unit), so for systems with Fahrenheit, it is converted twice again. To reword, the user sets the target temperature to 70F. VTherm saves this target temperature as 70. When reloading the integration, VTherm sets the target temperature to 70, but because the underlying entity is in Celsius (and therefore VTherm is too), #HA will convert this number again, resulting in 158 F being visible.

Putting all of this aside, the major issue with using VTherm with the default temperature set to F will result in the target temperature not being set properly. If I set VTherm to 68 F, the underlying entity will be set to 76 F. This is with regulation off, etc, so the underlying entity is just not being set properly. I confirmed that if I switch my HA unit to Celcius, this problem does not exist.

**Comment by mbbush** [comment] 2024-05-13 21:20
@mag2352 That's useful feedback, thanks!

For me, all my underlying entities are in Fahrenheit by the time they're exposed to HA, and my change resolved all my issues. Previously, the setpoints for each preset were undergoing a C -> F conversion each time I restarted HA, so after a few restarts it was trying to set my heat pumps to about 400 degrees F. It's a heat pump, not an oven!

I suspect that the biggest problem is https://github.com/jmcollin78/versatile_thermostat/pull/460/files#diff-2b96a6d22fdb5295d57d099f348d51ba2d2c4fbcc92490f320fcf515741437acR663-R667 using a different temperature scale depending on whether initialization is complete or not. 

@jmcollin78 Maybe a better solution to this problem would be to store the preferred unit in the VTherm config, based on either the unit of the underlying climate entity (if it's an over_climate type), or the default from the user's preferences, or perhaps allowing the user to override it. Then you could use *that* as the fallback for the cases where the underlying climate entity may not be available.

**Comment by mag2352** [comment] 2024-05-13 22:20
I have made some progress for my personal setup. I'm not going to bother making a PR, since many of these changes are hacky. Firstly, I changed the Unit of the VTherm itself:

https://github.com/jmcollin78/versatile_thermostat/blob/549423b313f7ca1966f55584bdd743813c2554ce/custom_components/versatile_thermostat/thermostat_climate.py#L901

I simply changed the lines that return the underlying entity's unit, and swapped it with HA's preferred unit. This made it so that I could reload the integration without the issue @mbbush described (C -> F conversion each time I restarted HA). The target temperature would be fine upon reboots. In addition, I could use sensors that are converted to Fahrenheit by HA automatically.

Obviously, this came with issues, and hence why I'm not sure if this is the way to go about things. Firstly, I'd like to note that the above change does have some merit to it; HA does not give the user the ability to change the unit of a single climate entity without changing all entities along with it. However, I feel like this change would break more things than fix them. For example:

I had to change set_temperature() in underlying,py, since cap_sent_values() uses the underlying entity's unit, and disagrees with the changes I made before. So, I simply removed the call to cap_sent_values() in the set_temperature() function:

https://github.com/jmcollin78/versatile_thermostat/blob/549423b313f7ca1966f55584bdd743813c2554ce/custom_components/versatile_thermostat/underlyings.py#L588

With these two changes, VTherm is usable for me if I don't use self-regulation. I'd like to note that HA's temperature converter could maybe be used here to resolve the issues in the cap_sent_values() function, but I didn't do this. The final change I made that allowed me to use self-regulation while using the device temperature offset is above this line, I added:

https://github.com/jmcollin78/versatile_thermostat/blob/549423b313f7ca1966f55584bdd743813c2554ce/custom_components/versatile_thermostat/thermostat_climate.py#L223

device_temp = TemperatureConverter.converter_factory(self.underlying_entity(0).temperature_unit, self.hass.config.units.temperature_unit)(device_temp)

This converts the temperature properly.

P.S. Why is the device offset added to the target temperature in the cooling mode? This is counter-intuitive. In fact, I think if the entity is in cooling move, the regulation should be subtracted (the opposite from heating). What I need from self-regulation, is the ability to use the device offset, I don't really care about the correction itself, just something I noticed.

**Comment by mag2352** [comment] 2024-05-14 18:26
I made a PR that addresses the issues that I have encountered. At this point, I believe it is working properly for me. Just to summarize, my HA preferred unit is F. All of my sensors and climate entities have an underlying unit of C, and HA automatically converts them to F. With the changes in the PR, the VTherm climate entity uses the preferred unit of HA to operate, removing the issue of conversion errors. This is inspired by BetterThermostat, which does the same thing.

**Comment by MattDahEpic** [comment] 2024-05-19 19:42
I installed the version 6.2.4.beta1 and it did not fix the issue. A freshly added thermostat-over-climate still suffers from the double conversion issue

**Comment by mag2352** [comment] 2024-05-19 21:07
@MattDahEpic You likely have the same setup I do (or close to that of my setup). 6.2.4beta1 did not fix my issue either. I made a PR earlier that fixed my issue, but it hasn't been reviewed/looked at yet.

**Comment by MattDahEpic** [comment] 2024-05-20 02:20
@mag2352 Your fork seems to work better, the freshly created entity is set to the converted value but once you set it manually it works as expected. Still plenty of quality-of-life features could be improved like the default min & max values or the defaultly created presets, but at least it works now!

**Comment by jmcollin78** [comment] 2024-05-30 07:45
Hello, is there any PR I can merge to try to fix this issue ?

**Comment by mag2352** [comment] 2024-05-30 14:14
> Hello, is there any PR I can merge to try to fix this issue ?

The PR linked above will resolve this issue. I'm still working on the other suggestions I made on the other posts, so I removed the subsequent commits in the above PR (so it only contains the fix for this double conversion issue).

**Comment by jmcollin78** [comment] 2024-06-10 16:48
I have merged the PR. Can someone give it a trhy please ? 

https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.2.4.beta2

**Comment by AlbertShovelton** [comment] 2024-06-11 11:16
Had the same issue and installed beta2. It seems to be working as expected.

**Comment by benjinne** [comment] 2024-06-11 13:07
beta2 works with me. I just had to adjust the min/max to make sense for °F

**Comment by jmcollin78** [comment] 2024-06-12 04:39
Fine. I will release this beta 2 so.

**Comment by jmcollin78** [comment] 2024-06-12 04:40
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.2.4

**Comment by jmcollin78** [comment] 2024-06-12 04:41
Thank you all guys for your help !

**Closed by jmcollin78** 2024-06-12 04:40 UTC
Labels: developed
