### ISSUE TITLE
Incorrect Temperature Reversion on Window Close

### ISSUE THREAD

**Issue by LennardPlay** [jmcollin78/versatile_thermostat#683] opened 2024-12-03 14:38 UTC
## Version of the custom_component
6.7.0

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: off, heat
min_temp: 5
max_temp: 30
target_temp_step: 0.1
current_temperature: 16.6
temperature: 19
friendly_name: Schlafzimmer
supported_features: 401
is_on: true
hvac_action: heating
hvac_mode: heat
preset_mode: eco
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 10
eco_temp: 19
boost_temp: 25
comfort_temp: 20.5
frost_away_temp: 10
eco_away_temp: 12
boost_away_temp: 18
comfort_away_temp: 16
power_temp: 13
target_temperature_step: 0.1
ext_current_temperature: 7.4
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: frost
saved_target_temp: 10
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: binary_sensor.schlafzimmer_fenster
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_frost_temp
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-12-03T14:50:14.661347+01:00
last_ext_temperature_datetime: 2024-12-03T14:50:14.661347+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 164.89
last_update_datetime: 2024-12-03T14:50:44.504844+01:00
timezone: Europe/Berlin
temperature_unit: °C
is_device_active: true
ema_temp: 16.6
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
is_over_climate: true
start_hvac_action_date: 2024-12-03T14:50:44.485509+01:00
underlying_entities: climate.schlafzimmer_heizkorper
is_regulated: true
regulated_target_temperature: 20.5
auto_regulation_mode: auto_regulation_medium
regulation_accumulated_error: -7.600000000000001
auto_fan_mode: auto_fan_none
current_auto_fan_mode: auto_fan_none
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
follow_underlying_temp_change: false
preset_modes: none, frost, eco, comfort, boost
```

## Describe the bug

When closing the window, the vtherm entity reverts to the last manually set temperature instead of applying the expected preset (e.g., frost).

I'm trying to:
Use automation to manage thermostat presets throughout the day:

    Evening: Set to comfort for warmth.
    Night: Switch to eco for sleeping.
    Morning: Transition to frost, as I don’t need heating during the day.

Vent the room in the morning after waking up -> radiator turns off and back on automatically 

I Occasionally, I manually raise the temperature (e.g., ~24°C) in the evening for extra comfort. The issue only occurs when I raised the temperature manually the evening before. 

And I expect:
The radiator should turn off when the window is opened.
Upon closing the window, the thermostat should return to the active preset (frost in the morning).

But I observe this ....
The radiator turns off when the window is opened (correct behavior).
When the window is closed, the thermostat reverts to the last manually set temperature (~24°C) instead of the expected preset.

Additional Context:
I rely on the preset functionality for automation, which works great otherwise. My schedule uses comfort in the evening, eco at night, and frost during the day. Occasionally, I manually increase the temperature for extra comfort, which triggers this issue when windows are opened and closed the following day.

## Debug log
I will upload it tomorrow after logging this event.

**Comment by Patdg** [comment] 2024-12-03 19:13
Same problem here. After opening detection, vrherl set comfort setting instead of previous setting.

**Comment by LennardPlay** [comment] 2024-12-04 10:42
> I guess that, if you change manually the setpoint when the window is open, this will override the saved preset and temperature. The human action is always prioritized.

I think there's a misunderstanding here. I'm not talking about changing the setpoint while the window is open, but the evening before.

1. Set the setpoint manually
2. Set setpoint via presets
3. Open window 
4. Close window
5. -> Setpoint reverts to value from step 1


> If you don't change the setpoint, can you confirm that it is working as expected ?

If I don't touch the setpoint, and do every change through presets everything works fine.

**Comment by LennardPlay** [comment] 2024-12-04 21:29
Thank you for your help. 
I'm afraid I'm also not able to reproduce it reliably. But it already happened about 10 times in the past, which is really frustrating due to wasted energy. I'll send you the attributes and log as soon as I'm able

**Comment by jmcollin78** [comment] 2024-12-04 21:35
I guess someone have change the setpoint when the window was open. That is the only explaination I see.

Don't hesitate to reopen, copy / paste the attributes (Development Tools / State) and look at the saved_xxx attributes when you will be able to reproduce.

**Comment by jmcollin78** [comment] 2024-12-05 19:28
The preset is set to `preset_mode: frost`. Is that not expected ? What was the state before the window is opened ?

The `saved_preset_mode: frost` shows that before opening the window, the preset was set to `frost` and this have been restored when the window is closed (this is current state when you take the attributes)

**Comment by LennardPlay** [comment] 2024-12-05 20:55
The preset frost is fine, but as you can see in the screenshot, the thermostat has a target temperature of 22.9°C after closing the window and doesn't adhere to the frost-temperature.

Before opening window: frost - 10°C
After opening window: frost - 22,9°C 

As you can see it reverts back to the temperature I set yesterday evening, while still remaining in frost mode. I have to manually activate another preset and then back again to have the right set-temperature of 10°C).

If I'm the only one experiencing this bug, maybe there's something wrong with my HA instance. Any ideas on how to fix this?

**Comment by jmcollin78** [comment] 2024-12-07 08:31
ok I understand better now. When you close the window, it restores the saved_temp which is 22,9
`saved_target_temp: 22.900000000000002` and not the `saved_preset_mode: frost`.

If I look in the code here is what I see:
```
            if self._window_action in [CONF_WINDOW_FROST_TEMP, CONF_WINDOW_ECO_TEMP]:
                await self._async_internal_set_temperature(self._saved_target_temp)
```
You configure the window detection to use preset frost `window_action: window_frost_temp`, so in that case  it is restoring the saved temp which is 22.9. So this seems wrong.
VTherm should restore the `saved_preset_mode: frost` and not the temperature. It is clearly a bug. which is only because you use the window action "set to frost".

I will fix that.

**Comment by jmcollin78** [comment] 2024-12-07 08:35
If you want to test quickly the patch (i'm on a big change now), you can change the line 2480 of base_thermostat.py with this one:
```
            if self._window_action in [CONF_WINDOW_FROST_TEMP, CONF_WINDOW_ECO_TEMP]:
                # issue 683 - await self._async_internal_set_temperature(self._saved_target_temp)
                await self.save_preset_mode(self._saved_preset_mode)
```
Be carefull to respect the indentation. If you are not used with code modifying, please wait for the next release.

**Comment by LennardPlay** [comment] 2024-12-07 11:10
Saved target temperature, in my case is always the last manually set temperature.

1. set temperature manually to X
2. Set climate to preset
3. saved_target_temp changes to X

To change it again it is necesarry to repeat both steps.

I don't know if this is intended behaviour, but this is how it works for my setup.

**Comment by jmcollin78** [comment] 2024-12-09 07:08
I have installed the beta and I will try to reproduce your case.
Is that the correct way to reproduce ?
1. set target manually to 19.3°,
2. set preset to Comfort (20°),
3. open the window and wait,
4. close the window and wait.

I should have the Comfort temperature 20° and you have the 19.3°.

Is that correct ?

**Comment by jmcollin78** [comment] 2024-12-09 07:26
It seems to work here are the steps:

0. before
![Capture d’écran 2024-12-09 à 08 14 03](https://github.com/user-attachments/assets/0e2bf807-8d9a-4c08-b8ff-9e422f0999ee)
1. set manually to 19.5,
![Capture d’écran 2024-12-09 à 08 14 59](https://github.com/user-attachments/assets/1bb36e6f-f93d-4273-ab10-84a0fb67fbe6)
2. set preset comfort
![Capture d’écran 2024-12-09 à 08 15 20](https://github.com/user-attachments/assets/74fd0631-7950-4abe-856c-68f96d1ed6c2)
3. open the window
![Capture d’écran 2024-12-09 à 08 21 14](https://github.com/user-attachments/assets/ee00f08e-a76d-44d6-a1f1-f7458e163380)
4. close the window.
![Capture d’écran 2024-12-09 à 08 22 38](https://github.com/user-attachments/assets/be39f031-0987-41a5-ab0b-4f8ab54956b3)

After closing the window, the target is restored to 20° (Comfort for me) and the preset never change. This is what is expected.

It could be great if you can do the same journey if the issue is not fixed for you.

**Comment by Patdg** [comment] 2024-12-09 08:11
Hope it will fix this issue.I have the same kind of problem and during « edf tempo red days » it will save some extra euros !Thank you for your support !Patrick (France - 78)Le 9 déc. 2024 à 08:26, Jean-Marc Collin ***@***.***> a écrit :﻿
It seems to work here are the steps:

before
Capture.d.ecran.2024-12-09.a.08.14.03.png (view on web)
set manually to 19.5,
Capture.d.ecran.2024-12-09.a.08.14.59.png (view on web)
set preset comfort
Capture.d.ecran.2024-12-09.a.08.15.20.png (view on web)
open the window
Capture.d.ecran.2024-12-09.a.08.21.14.png (view on web)
close the window.
Capture.d.ecran.2024-12-09.a.08.22.38.png (view on web)

After closing the window, the target is restored to 20° (Comfort for me) and the preset never change. This is what is expected.
It could be great if you can do the same journey if the issue is not fixed for you.

**Comment by Patdg** [comment] 2024-12-09 14:17
I do not have a process to create the issue. Will try to reproduce it before installing the patch. By the way, I’m still new to HA and don’t know how to install a beta release. Any tuto or link to share ?RegardsPatrickLe 9 déc. 2024 à 11:24, Jean-Marc Collin ***@***.***> a écrit :﻿

Hope it will fix this issue

Can you try https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.2.beta1 ?
At home I cannot reproduce the issue

**Comment by jmcollin78** [comment] 2024-12-09 16:32
to install a beta, just go to HACS and select explicitly the release you want to install. By default you have the last one only.

**Comment by LennardPlay** [comment] 2024-12-09 17:41
I'm sorry to tell you this, but after the beta update things are even weirder now:

1.  I set temperature manually (23,8°C) 
![grafik](https://github.com/user-attachments/assets/45c46b4f-5676-4180-b876-c66fddc8200f)
saved_preset_mode: frost
saved_target_temp: 19

2. I activate frost preset 
![grafik](https://github.com/user-attachments/assets/e5590ea9-64c5-401f-89f3-d24eca50a641)
saved_preset_mode: frost
saved_target_temp: 19

3. I open window
![grafik](https://github.com/user-attachments/assets/34d65341-ec15-47a8-a73f-70a9fdc7cf4e)
saved_preset_mode: frost
saved_target_temp: 19

4. I close the window 
![grafik](https://github.com/user-attachments/assets/d7cc17ba-216e-4b98-bdec-5a60ffeed97a)
saved_preset_mode: frost
saved_target_temp: 19

Please let me know if there is anything I can do to help fix this issue

**Comment by jmcollin78** [comment] 2024-12-09 18:42
Ooooh so bad. I don't see any difference with my tests... Can figure out what happens.

You can set the window action to Turn off while waiting for a hypothetic fix.

**Comment by LennardPlay** [comment] 2024-12-10 15:43
> You can set the window action to Turn off while waiting for a hypothetic fix.

I already selected turn_off as window action. Issue still remains :/

**Comment by jmcollin78** [comment] 2024-12-10 17:55
There is a big misunderstanding then. With "turn_off as window action" the saved_target_temp is not restored. Only the hvac_mode. There is something weird.

**Comment by LennardPlay** [comment] 2024-12-12 16:58
I changed the window_action to in hope, it would fix the issue for now. Seemingly it doesn't

Something really weird is going on here. Any ideas on how to troubleshoot?

**Comment by jmcollin78** [comment] 2024-12-17 22:18
Your attributes says you are with that window_action: `window_action: window_frost_temp`. 
My advice was to change to 'Turn off' the window action while waiting for a fix. I use it all days so I'm sure it is working.

I need to investigate and eventually fix the issue with the window_frost_temp action.

**Comment by TTLucian** [comment] 2024-12-17 23:09
I have the same issue, I think. I use binary sensors, window_action: window_turn_off, window_delay_sec: 600. Set temp is 22. I open the window, after 10 minutes hvac_mode switches to off, set temp switches to 7 degrees. I close the window, again after 10 minutes hvac_mode switches to heat but the temperature stays at 7 degrees.
And another problem is that after closing the window it applies the window_delay_sec setting before turning to heat again. I was expecting that heating would be resumed as soon as I close the window.

**Comment by jmcollin78** [comment] 2024-12-18 21:22
Hello @TTLucian ,

In `window_action: window_turn_off` VTherm don't touch the preset and VTherm don't set the temperature.

Can you check if you have the 'follow underlying...' checked and try with uncheck.

<img width="255" alt="Capture d’écran 2024-12-18 à 22 18 56" src="https://github.com/user-attachments/assets/b6258cc3-f447-40d3-b80e-8da96bbb7a13" />

Have you a preset to 7° ? I wonder if your device change its target temperature to 7° when it is turned off.

**Comment by TTLucian** [comment] 2024-12-18 21:35
I think I've found the reason. The devices are Sonoff  zigbee TRV's with Zigbee2mqtt. I found the setting in z2m "Frost protection temperature: Minimum temperature at which to automatically turn on the radiator, if system mode is off, to prevent pipes freezing." which is set at 7 deg. I've set vtherm's window_action to window_frost_temp and now it correctly reverts to previously set temp when closing thw window. Thanks for pointing me in the right direction.
Is there any way I can get rid of the delay after closing the window so that heating starts immediately?

**Comment by jmcollin78** [comment] 2024-12-18 21:51
> Is there any way I can get rid of the delay after closing the window so that heating starts immediately?

There is one delay for opening and closing. I do not intend to change this?

**Comment by TTLucian** [comment] 2024-12-18 21:54
I don't see a reason for a delay after closing the window, but, ok. I guess I'll have to use an automation.

**Comment by jmcollin78** [comment] 2024-12-18 21:55
It is also my opinion but some people wants to let the room heat itself "naturally"  before turning on the heater.

**Comment by jmcollin78** [comment] 2024-12-18 21:56
@LennardPlay as you can see it seems that is it working with window_action: window_frost setting for @TTLucian .

**Comment by TTLucian** [comment] 2024-12-18 21:59
> It is also my opinion but some people wants to let the room heat itself "naturally" before turning on the heater.

That's why I previously suggested to "add a second delay for window closed (window_open_delay_sec and window_closed_delay_sec)."

**Comment by jmcollin78** [comment] 2024-12-18 22:10
Yes I remember. You are not the first one.

**Comment by LennardPlay** [comment] 2024-12-19 17:50
@jmcollin78 
I have to say that I sadly can't even reproduce the problem with another vtherm. What can I do to completely reset a vtherm? I already tried to delete it and add it again, but error still exists.

**Comment by jmcollin78** [comment] 2024-12-20 07:40
@LennardPlay deleting and recreating is the only way to reset a Vtherm but is generally not needed. If you still have the issue, it means the reason is elsewhere. Maybe something with the sensor ? You can to switch the sensor from the working VTherm to the one in default and see if you reproduce.

**Comment by fdfdgsgsdfas** [comment] 2024-12-22 07:45
The VTherm Integration is great and I love the valve positining with my Sonoff TRVZB. 
With Version 6.8.3 the window open feature does not set the previous preset after the Windows is closed. The status changes back Formell "off" to "heat" but the target temperature keeps staying at 7°C instaed of changig back to the e.g. ECO preset.
If I remember correctly the feature was Wirkung AS expected with version 6.8.2.

**Comment by jmcollin78** [comment] 2024-12-22 10:24
Hello @fdfdgsgsdfas 

> but the target temperature keeps staying at 7°C instaed of changing back to the e.g. ECO

See https://github.com/jmcollin78/versatile_thermostat/issues/683#issuecomment-2552291682
I think you are exactly in the same case as above. Your Sonoff turns itself to 7° and Vtherm follow this change.


For All:
The objective of the window action 'turn off' is to ... turn off the device without touching any setting you does or the Scheduler does : preset and target_temperature for instance.

With that behavior is the Scheduler change to 'Boost', the restored state after closing the window is not the preset before opening but the last preset sets by the Scheduler. Else you will loose the last scheduler change (and make an issue ...).

For window action 'anti frost', the behavior is quite the same: VTherm change its target temperature to frost (let says 10) but don't touch the preset nor the hvac_mode (Heat). When the window is closed, the restored state is the current preset AND not the previous preset (before opening). That is a feature and not an issue.

And all my tests shows that it is working fine. There are many automated tests on this part and all are fine.

II hope it is more clear now.

**Comment by jmcollin78** [comment] 2024-12-22 14:49
Finally I find a non working case and I will fix it in the next release.
https://github.com/jmcollin78/versatile_thermostat/pull/734

**Comment by jmcollin78** [comment] 2024-12-22 16:52
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.8.4

**Closed by jmcollin78** 2024-12-22 16:52 UTC
Labels: bug, developed, P1
