### ISSUE TITLE
Self-regulation over AC-Heatpump. Need the adaption to also SUBTRACT to the underlaying setpoint - not just add

### ISSUE THREAD

**Issue by gunmalmg** [jmcollin78/versatile_thermostat#188] opened 2023-11-11 21:57 UTC
Again - Thank you for a great thermostat integration - and for the new Self-regulation function. 👏

But it seams that the adaption don't have the ability to subtract to the underlaying set point if the room temperature is higher than the set-point. 

I Have a AC-Heatpump that needs a overlaying regulation to better keep my set-temp in the room. 
That implies both the need to increase and decrease the underlaying AC-heatpunmp set-point. 
But it seams that the adoption algorithm just handle increasing. The results in the romtemperature to be constantly higher than desired when the AC-heatpump needs to lover it set point. 

Hope this can bee solved :-) 

Regards 
Gunnar 

Hope the screenshots illustrates the challenge. 

![Bilde 11 11 2023 klokken 17 31](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/42edcf09-d0af-4aac-a1fd-2c2052b88352)

![Bilde 11 11 2023 klokken 22 56](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/a2768618-e936-447c-bcba-5eaa0c41ea23)

![Bilde 11 11 2023 klokken 22 49](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/36e5dffc-767d-4821-ad7f-d77e0593a688)

**Comment by maia** [comment] 2023-11-11 22:11
Gunnar, could you post a screenshot of a history chart including the versatile thermostat climate entity, the "regulated temperature" entity for that room and the room temperature sensor, for a range of a few hours, so one can see the swings? Also, which settings are you using for the regulated temperature? (light, medium, strong, slow, minimum period)

**Comment by gunmalmg** [comment] 2023-11-11 23:08
Hi Maia

I use Medium regulation setting now(tried Strong first)

It's not so much swing in the regulated temperatures now - but that's because it has stabilised this last hours. 
The regulation has stabilised on a rom-temperature around 23-24c although my VT-Setpoint is 22c. 
The underlaying AC-Heatpump receives a set point at 22.5c - witch get rounded up to 23c on the AC-Heatpump that only operates on whole degrees. 
But the regulation algorithm never seems to regulate the underlaying set-point to a temperature under set VT-Setpoint. 
I think that's the problem. It seems that it never subtracts - only adds - to the underlaying set-point. 

Regards
Gunnar 


![IMG_3318](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/bc103a75-770a-4ff6-985b-5f1d767f8501)

![Bilde 12 11 2023 klokken 00 04](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/7a6ea3d1-21ad-4dda-902b-d0541f51de28)

**Comment by maia** [comment] 2023-11-11 23:19
Gunnar, I‘m not familiar with heatpumps, but all I can say is that the regulation also subtracts. Can you create a graph including the regulated temperature? Thanks!

**Comment by jmcollin78** [comment] 2023-11-11 23:26
I can confirm the regulation is subtracting when needed. You should have start with the lower regulation like indicated in the documentation: Light.
What you are experiencing is certainly an over regulation, because Medium parameters seems too high for your case.

**Comment by gunmalmg** [comment] 2023-11-11 23:46
OK. 
I thought the regulation levels related to how many degrees the regulation could max regulate. 
Light = 1c
Medium=2c
Strong=3c
Maybe I misinterpreted the documentation on that point.

I will now try the Light setting :-) 

Then we'll see
Than you for your swift response. 

Regards Gunnar

**Comment by jmcollin78** [comment] 2023-11-12 00:07
>  how many degrees the regulation could max regulate.

Not only. Also the strength (speed) of regulation. Too much will overshoot the target (what you have experienced).

**Comment by gunmalmg** [comment] 2023-11-12 10:38
Now I have tested with Light setting thru the night. And restarted HA to test if the regulation manage to subtract if the room temp is to hot. 
It don't seem to subtract. The regulated temp just stabilise 1 degree over the desired rom set temp. Even when the room is ≈1c over the desired rom set temp. 

My son has also challenges with this regulation, and his findings suggests that the regulation only apply subtraction if the setpoint is lover then about 21c. Is that possible ??. Is so - we may solve the issue with an ability to adjust that "tipping point" in the regulation ??

Info: 
We live in Norway and we do a lot of our heating with heat-pumps.  heat-pumps is exactly the same as a AC and can change the temperature in a rom fast. 

Hope we can solve this :-) 

Regards Gunnar


![Bilde 12 11 2023 klokken 11 17](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/9ec8056e-5bba-46dc-9919-88e69a6b8fe7)

Here is the State attributes:

```
hvac_modes:
  - cool
  - heat
  - dry
  - heat_cool
  - fan_only
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes:
  - quiet
  - low
  - medium
  - medium_high
  - high
  - auto
  - strong
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - stopped
  - fixedtop
  - fixedmiddletop
  - fixedmiddle
  - fixedmiddlebottom
  - fixedbottom
  - rangefull
current_temperature: 23.3
temperature: 22
fan_mode: auto
preset_mode: none
swing_mode: rangefull
hvac_action: null
hvac_mode: heat
type: null
eco_temp: 20
boost_temp: 30
comfort_temp: 23
eco_away_temp: 10
boost_away_temp: 10
comfort_away_temp: 10
power_temp: null
ext_current_temperature: 1.3
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 22
saved_hvac_mode: null
window_state: "off"
motion_state: null
overpowering_state: null
presence_state: "on"
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2023-11-12T11:17:12.266402+01:00"
last_ext_temperature_datetime: "2023-11-12T11:17:34.950977+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2023-11-12T11:17:34.957717+01:00"
timezone: Europe/Oslo
window_sensor_entity_id: null
window_delay_sec: null
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: input_boolean.hjemme_status
power_sensor_entity_id: null
max_power_sensor_entity_id: null
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.vinterhage_hjemme
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
regulated_target_temperature: 22.5
regulation_accumulated_error: -10
friendly_name: VT_VP_Vinterhage
supported_features: 57
```

**Comment by jmcollin78** [comment] 2023-11-12 10:53
Hi @gunmalmg ,

With your parameters I see:
1. target temp is 22°,
2. temp is 23,3°,
3. external temp is 1.3°

The light configuration is the following:
    kp:float = 0.2
    ki:float = 0.05
    k_ext:float = 0.05
    offset_max:float = 1.5
    stabilization_threshold:float = 0.1
    accumulated_error_threshold:float = 10


So the difference between external and temp is 22°. With a Light configuration this means that the correction for external temp is 0.05 x 20 -> 1°.

I see the error is `regulation_accumulated_error: -10` which means that the regulation algorithm is decreasing the regulated by -10*0.05 -> 0,5°. So the calculated regulation is +0,5°.  Which is correct but since too much for you.

I suggest you to use the 'Slow' configuration which will much take care of the accumulated error.

I hope we will find the correct tuning.

I will change the default values of the regulation algorithm considering your result.

For your information, this feature is very yoing (introduced two weeks ago) and need more tuning with more extrems temperatures.

**Comment by gunmalmg** [comment] 2023-11-12 11:07
I am aware that this feature is very young and I applaud you for putting effort in to this function. I do not want to criticise - I just want to contribute to a well function function. 😀

I actually have this functionality to day through a Norwegian cloud service - that overrides the heatpumps that I have. It regulates very well. But I don't want to be dependent of a cloud service - I would like it to bee managed locally. Therefor I applaud you effort so much. 

I'l be happy to contribute more. 
First I will try the Slow-mode as you suggest. 

Regards Gunnar

**Comment by jmcollin78** [comment] 2023-11-12 11:51
And you already have the Cloud service as now ?
This could explain why target is so high. Two regulation mecanisms are not supposed to works well.

> First I will try the Slow-mode as you suggest.

Maybe we will have to tune a little more after this change but this should be better if I understand well your case.

**Comment by gunmalmg** [comment] 2023-11-12 16:30
I have detached that cloud-service in advance. 
Noting other than the Versatile Thermostat is giving input to the AC-heatpump. 

I have now run the VT in Slow-mode for several hours and it have loverd the regulated temperature by 0.5c. Not enough to reduce the rom temp. 
I think you have to take in to the equation the consecutively difference  between the actual rom temperature and the desired set temp. A AC-Heatpump is a rapid heat source and can respond to regulation relatively fast.  So a regulation should respond relatively fast also. Example : when the sun come in to the windows an heat up the rom - the regulation should respond by turning down the regulated temp relatively fast -( when the regulation senses the rapid increase in rom temp caused by the sun or something else.)

![IMG_3341](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/f3be6845-511f-4837-85c4-54fb1573cd2a)


hvac_modes:
  - cool
  - heat
  - dry
  - heat_cool
  - fan_only
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 1
fan_modes:
  - quiet
  - low
  - medium
  - medium_high
  - high
  - auto
  - strong
preset_modes:
  - none
  - eco
  - comfort
  - boost
swing_modes:
  - stopped
  - fixedtop
  - fixedmiddletop
  - fixedmiddle
  - fixedmiddlebottom
  - fixedbottom
  - rangefull
current_temperature: 23.5
temperature: 22
fan_mode: auto
preset_mode: none
swing_mode: rangefull
hvac_action: null
hvac_mode: heat
type: null
eco_temp: 20
boost_temp: 30
comfort_temp: 23
eco_away_temp: 10
boost_away_temp: 10
comfort_away_temp: 10
power_temp: null
ext_current_temperature: 2.2
ac_mode: true
current_power: null
current_power_max: null
saved_preset_mode: none
saved_target_temp: 22
saved_hvac_mode: null
window_state: "off"
motion_state: null
overpowering_state: null
presence_state: "on"
window_auto_state: "off"
window_bypass_state: false
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2023-11-12T17:27:12.278766+01:00"
last_ext_temperature_datetime: "2023-11-12T17:14:36.654560+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 0
last_update_datetime: "2023-11-12T17:28:13.674209+01:00"
timezone: Europe/Oslo
window_sensor_entity_id: null
window_delay_sec: null
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
motion_sensor_entity_id: null
presence_sensor_entity_id: input_boolean.hjemme_status
power_sensor_entity_id: null
max_power_sensor_entity_id: null
is_over_climate: true
start_hvac_action_date: null
underlying_climate_0: climate.vinterhage_hjemme
underlying_climate_1: null
underlying_climate_2: null
underlying_climate_3: null
regulated_target_temperature: 22
regulation_accumulated_error: -180.99999999999991
friendly_name: VT_VP_Vinterhage
supported_features: 57

**Comment by jmcollin78** [comment] 2023-11-12 16:58
> I think you have to take in to the equation the consecutively difference between the actual rom temperature and the desired set temp. A AC-Heatpump is a rapid heat source and can respond to regulation relatively fast. So a regulation should respond relatively fast also

I know and this is what is done by the algorithm.

So this is much better:
```
regulated_target_temperature: 22
temperature: 22
regulation_accumulated_error: -180.99999999999991

hvac_action: null.    -> your AC device don't heat
```
Regulation is 0. Nothing is heating and your room is at 23,5°. This is not a matter of regulation. This is like you have something else that produce heat in your house (a heater ? the sun ?).

Can you check that your AC device don't heat. I guess it is so.

**Comment by gunmalmg** [comment] 2023-11-12 18:02
It's in Heat state. See the screenshots of the Underlaying AC-Heatpump. 
The only thing that has happened is that the regulated temp is reduced to 22c 


![IMG_0252](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/9f8e0e14-75da-46b4-a08c-eff4ebae632a)
![IMG_0250](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/4c9cb8b5-4bfa-4c67-9d71-173f0cbfa47d)

**Comment by gunmalmg** [comment] 2023-11-12 18:05
![Bilde 12 11 2023 klokken 19 04](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/ba5b9f66-6203-416e-9281-783c2ae5724f)

**Comment by jmcollin78** [comment] 2023-11-12 18:08
ok. If your heatpump heats when current temperature is 1,5° above the target, then you need a very special set of parameters and I don't have this now out of the box. We need to amplify the negative value.

Is that a normal behaviour for you AC-heatpump ? It seems so strange to me...

**Comment by gunmalmg** [comment] 2023-11-12 19:35
I don't understand what is so strange. 
In the same way that a underlying thermostat needs to be increased 1-3 degrees some times to reach the desired set-temp(rom-temp), it is also need for a underlaying thermostat to be reduced 1-3 degrees some times when the room temp exceeds the desired set-temp(rom-temp). This is regardless off what is the cause off this. 

I have heat pumps (air to air) that needs increased regulating setpoint, and I have heatpumps that need reduced regulated setpoint to reach the target setpoint. 
There are many factors influencing this - and I don't think that's possible to put all this factors in to a formula. I think we just have to monitor the rom-temp and compare to the desired set-point , and then try to adjust de regulated setpoint accordingly. With some clever logic. 

The given heat pump I am mentioning here is a pump that is influenced by a nearby kitchen , sometimes the direct sun and the fact that the pump i mounted on a outer wall that "fools" the pump to think it is colder then it actual is in the room-temp(in the wintertime). This is factors that you can't process in a function, but can be observed by the difference in measured rom-temp compared to set-temp. 

Hope this was understandable 

Regards Gunnar

**Comment by jmcollin78** [comment] 2023-11-14 06:48
Hello @gunmalmg,

I clearly understand but it is the first time I see a heatpump that continue to heat while room temperature is largely above the target. That is w-hy regulation don't works.

Anyway I have made a special set of parameters for your case, that forget the external temp and concentrate on the error (target temp - room temp) with a large capacity of regulation (until 5 degres).

To test this set of parameter, you have to install the `main` branch of VTherm like this:
![Capture d’écran 2023-11-14 à 07 34 34](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/c2fcaaed-6bef-4c22-a25f-5df79d85823a)

and then choose the 'Strong' auto-regulation mode in the configuration panel of your VTherm.

The parameters are the following:
```
class RegulationParamStrong:
    """Strong parameters for regulation
    A set of parameters which doesn't take into account the external temp
    and concentrate to internal temp error + accumulated error.
    This should work for cold external conditions which else generates
    high external_offset"""

    kp: float = 0.4
    ki: float = 0.08
    k_ext: float = 0.0
    offset_max: float = 5
    stabilization_threshold: float = 0.1
    accumulated_error_threshold: float = 50
```

If they works as expected I will integrate them in the next release.

**Comment by gunmalmg** [comment] 2023-11-14 22:18
Thank you wary much. 
I will try that :-) 
I assume I have to restart HA after redownload the Main-version 

I actually have 5 heat pumps in my house -that acts differently. They are of different brands and are placed in different rooms(climate environments).
I have now made a panel with graphs for each of them, and highlighted the essential states/values : VT Set-Temp / VT Regulated Temp / Underlaying(Heatpump) Set-Temp and Room Temp. You can also see the ext temp in a separate graph. 
Heatpump#1-#4 is regulated by VT. Heatpump#5 is regulated by a cloud service that do the same job as your VT - Just for comparison. To see if there is sorting to pick up by its handling. 

It's the Heatpump#1 that we are working on. It is placed in a Veranda/Orangerie(if I use the right terms) that is a extension to the kitchen. The heatpumps#2-#4 is in places that need raising the underlaying temperature, so that seems to function well. Heatpump#5 (that is regulated by a cloud service) is in then Master bedroom witch need sometimes need to get de underlaying set-temp reduced under the desired set-point (se graph)

A thing that I have noticed by looking at this graphs is that the VT regulates/moves the "regulated temperature" by 0.5 degrees. But the heat pump only operates by whole degrees. So when the VT regulates down the "regulated temperature" by 0.5c it got rounded up by the Heatpump and thus not changes. (se graph for Heatpump#1)
Maybe this is something to consider 

I come back with updatet graphs tomorrow. 

![4755B771-7A26-49BE-AE66-BE76D8FAFD6A_1_201_a](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/649663fe-9fd4-478a-b8ba-5c12b0a49b69)

**Comment by jmcollin78** [comment] 2023-11-15 06:33
#1 is too high for a target at 23° but it is certainly related to the .5 precision which is not used (and rounded above I guess ?). The graph is good for a target at 24°

#2, #3 and #4 are perfect for me.

#5 is too high (but it is the cloud provider).

> VT regulates/moves the "regulated temperature" by 0.5 degrees

You can change this in the configuration with this parameter (in French sorry):
![Capture d’écran 2023-11-15 à 07 30 37](https://github.com/jmcollin78/versatile_thermostat/assets/1712374/0469579d-e16b-440e-8530-834b69aea498)

Set it to 1 instead of 0.5 if your pump doesn't support more precision (which is a shame for precision).

What I see here is good for isn't it ? Not perfect for #1, see if changing the above parameter will change the behaviour of #1.

**Comment by gunmalmg** [comment] 2023-11-15 21:26
Hi

Here is the graphs from the last 6 hours. 
It seams that #1 is regulating fine after your spasialcode. Great 👏. We must monitor it some more to se if it works over time. But so fare so good. 

But for #2 and #4 that i didn't alter from Medium-mode, they have started to heat to much after you spasialcode. They regulated fine in Medium-mode before. You see if this has a logical explanation regarding your spesialcode or not. 
I have special focus on #2 that's in the hall and regulated nicely with the standard code. 

Question: Regarding the 0.5c regulation setting. 
If i alter the setting from 0.5c to 1c : Howe vill that affect the regulated temp ?  Vill the regulated temp just wait until it change with minimum 1c ?. If that's the case - I vill assume that the altering from 0.5c to 1.0 would not have any effect on the underlaying set-temp. Am i right ? or is it so that a calculated regulation change of 0.5c would be altered to a 1.0c change on the underlaying set-temp ??

![IMG_3354](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/4ad3afe2-d9f1-4c4b-9eab-0b738cf0ff0d)


![IMG_3355](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/05856ab0-6e63-4aeb-a20e-b9fc3a876bc9)

**Comment by jmcollin78** [comment] 2023-11-16 18:56
Hello @gunmalmg 

> It seams that https://github.com/jmcollin78/versatile_thermostat/issues/1 is regulating fine after your spasialcode.

Great news !

> But for #2 and #4 that i didn't alter from Medium-mode, they have started to heat to much after you spasialcode.

You should set also this VTherm to the Strong regulation. I didn't change anything in the configuration of the Medium mode but when it will be cold, the external temp factor will be too much valued. This is fixed in the Strong mode (which should not be so strong).

> Vill the regulated temp just wait until it change with minimum 1c ?

Yes exactly what it does.

> or is it so that a calculated regulation change of 0.5c would be altered to a 1.0c

No. If the offset is below 1°, no offset will be applied. So for 0,5 -> 0, 0,999 -> 0, 1 -> 1, 1.000001 -> 1

**Comment by jmcollin78** [comment] 2023-11-17 22:56
Fixed in 4.1.0. Keep the Strong regulation algorithm

**Closed by jmcollin78** 2023-11-17 22:56 UTC
Labels: developed

**Comment by gunmalmg** [comment] 2023-11-18 20:27
Thanks 

This enhancement is essential to us up north 🥶😀 - in the wintertime. 


As a treat I attached a screenshot that showes how the Strong algorithm functions well at my cottage this weekend with outdoor temp dropped under -20c.  See the Outdoor graph and the Room temp 👏
(I have a heatpump that actually is capable of pulling heat out off -20c :-) 


I hope that you also will find time and interest in working on the enhancement suggestion I posted regarding the need to be able to alter the temp-presets through the UI and not have to let users get access to the whole VT-config. In the North we have to tweak/alter this presets during the changing seasons. 
(https://github.com/jmcollin78/versatile_thermostat/issues/186#issue-1989056129)

Regards Gunnar

![IMG_3371](https://github.com/jmcollin78/versatile_thermostat/assets/128496535/bfeb962c-504d-4be9-95aa-67a0e6d21f86)

**Comment by jmcollin78** [comment] 2023-11-18 22:16
Very glad to see this good curve. With -21° outside, what is important for you is to have a k_ext (coef for external temp - target_temp) to 0 else it will take too much value and a capability to regulate at a high level (you are almost at + 3°).

> I hope that you also will find time and interest in working on the enhancement suggestion

This is a nice to have. I'm not the UI specialist but I will have a look in the next weeks, I promise. I have still a lot to do with self-regulation, window open detection and "must have" features. Be patient please, and you don't need to recall me this feature. It is written.

**Comment by gunmalmg** [comment] 2023-11-20 19:19
A little ting that needs to ble solved regarding the Strong-regulation.(and maybe the other levels also)
The Heatpumps have a temperature operation range that can vary from model to model. My models are of two kind. #1,#5 and #6 operates from 10-30c, and the others from 16-30c. 
It occurs a problem when the Regulated temperature issues a temperature that is lower (or maybe higher) than the operation range for the underlaying heatpump. The underlaying heatpump simply ignore then new Regulated temperature value if its out of its operation range. 
So when I e.g. leave my cottage and lower the VTSet-Temp fra 23c to 10c - the Regulated temperature respond by trying to set the underlaying set-temp to 5c. But since the temperature is outside the temperature operation range of the heatpump, the heatpump simply ignores it and keeps the set point it had before the regulation. 
The result of this is that the VT-termostat shows 10c set temp, and 5c Regulated temp, but the underlaying heatpump hase kept its previous set-temp - which is e.g. 25c. 
Maybe this hase to be solved by 2 ekstra configuration settings - min and max operation temp for the underlaying unit, and that the algorithm keeps the regulated temp inside these boundaries. 
Regards Gunnar

**Comment by jmcollin78** [comment] 2023-11-21 07:33
Understood. Can you please open a new issue with only this feature request ? Thank you
